{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.sms",
    "version": "13.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo.modules.sms-13.1.4.aar",
          "url": "expo.modules.sms-13.1.4.aar",
          "size": 18931,
          "sha512": "42be0c174f4263ac79836bf3f925b17e340b5169d1bdffde33f113b6bf428c98c27bb86073976eaec8201f8a85b1554f55ee1899a37192da829a95ea12a8b49d",
          "sha256": "9b0fe94b3fc57bbca337c9f95fd4d8d2e5774cf430cb5ffe90eb004b71051f02",
          "sha1": "7f507b11b21dd72c7a3b14d1d3ef4260ee4a762d",
          "md5": "9c85ce2daacc04d466b07468106c0809"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.sms-13.1.4.aar",
          "url": "expo.modules.sms-13.1.4.aar",
          "size": 18931,
          "sha512": "42be0c174f4263ac79836bf3f925b17e340b5169d1bdffde33f113b6bf428c98c27bb86073976eaec8201f8a85b1554f55ee1899a37192da829a95ea12a8b49d",
          "sha256": "9b0fe94b3fc57bbca337c9f95fd4d8d2e5774cf430cb5ffe90eb004b71051f02",
          "sha1": "7f507b11b21dd72c7a3b14d1d3ef4260ee4a762d",
          "md5": "9c85ce2daacc04d466b07468106c0809"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.sms-13.1.4-sources.jar",
          "url": "expo.modules.sms-13.1.4-sources.jar",
          "size": 2926,
          "sha512": "cc89b7a8ca078852f0556cc75ce5776a550cb9d8571f03556e268dda1fcf6c30c1b5da7564d7a7e19a45e9f20f871fd6a1e677a40fb41858d8205058baf9b590",
          "sha256": "768553750e1ebc22c744ac587d7b126c5100bd66084d66559e757b22b8bc3561",
          "sha1": "241ecb0c9009cd00b658ee43b1e6f5c11a6e2a0f",
          "md5": "026cedab492225cc808f8d1e8a632545"
        }
      ]
    }
  ]
}
