{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.network",
    "version": "7.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo.modules.network-7.1.5.aar",
          "url": "expo.modules.network-7.1.5.aar",
          "size": 18567,
          "sha512": "deaf317ad3295fed52319037bf5bd3373d4680da867cb5836838a028d873fbf34dcd42903b5fa9ec950af1a3986216a7390803249d377029d2adf1e750d20b42",
          "sha256": "e1d417a09f6de53af4b488b3b4fe52371238d9dfcc20b593f4bc8f315ab87725",
          "sha1": "f6921852d2693d9b174fb9c4245746b9c012d9d3",
          "md5": "dabf6314a916dbd6115cc9ba80aa2ec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.network-7.1.5.aar",
          "url": "expo.modules.network-7.1.5.aar",
          "size": 18567,
          "sha512": "deaf317ad3295fed52319037bf5bd3373d4680da867cb5836838a028d873fbf34dcd42903b5fa9ec950af1a3986216a7390803249d377029d2adf1e750d20b42",
          "sha256": "e1d417a09f6de53af4b488b3b4fe52371238d9dfcc20b593f4bc8f315ab87725",
          "sha1": "f6921852d2693d9b174fb9c4245746b9c012d9d3",
          "md5": "dabf6314a916dbd6115cc9ba80aa2ec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.network-7.1.5-sources.jar",
          "url": "expo.modules.network-7.1.5-sources.jar",
          "size": 3501,
          "sha512": "465314d412f6e04a110db4aa7eb070dd8b6cf213037e88e744bb0d8841508f16564a8ca1ba8445de77289b97a443133759fca7eeabab974fe8b14b6513d1236f",
          "sha256": "4efcfff7fa9f1ba38e4314bbb3574e5ad6c683f0dc3fb837f32424ffb8401b7a",
          "sha1": "a4f2ecd7cd71cdebb304b4d06cea707be32c4de4",
          "md5": "715d634dd42d9a4f5166fc43d6863d4e"
        }
      ]
    }
  ]
}
