{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.cellular",
    "version": "7.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo.modules.cellular-7.1.4.aar",
          "url": "expo.modules.cellular-7.1.4.aar",
          "size": 23775,
          "sha512": "c8b9ddd367f97867d5ce97b2bc59ee6de829882b9d98681f154a8c353b903d09a231b57e59baac3d29d08d0db5406baa09b25b5bb51fd2b431dfc06fccf5ddbc",
          "sha256": "198b1e1c62e2787209fd91e1a3ebf90bf139631112d3e4208ba5c215a912a5f3",
          "sha1": "6e59b61ac94570f5465189969e9e0b29bda646ac",
          "md5": "4fe17926743f9c99cc5c39578535e1f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.cellular-7.1.4.aar",
          "url": "expo.modules.cellular-7.1.4.aar",
          "size": 23775,
          "sha512": "c8b9ddd367f97867d5ce97b2bc59ee6de829882b9d98681f154a8c353b903d09a231b57e59baac3d29d08d0db5406baa09b25b5bb51fd2b431dfc06fccf5ddbc",
          "sha256": "198b1e1c62e2787209fd91e1a3ebf90bf139631112d3e4208ba5c215a912a5f3",
          "sha1": "6e59b61ac94570f5465189969e9e0b29bda646ac",
          "md5": "4fe17926743f9c99cc5c39578535e1f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.cellular-7.1.4-sources.jar",
          "url": "expo.modules.cellular-7.1.4-sources.jar",
          "size": 2471,
          "sha512": "ab485566e6ad6812c22b8951a3f983c8956d63c1f6cbe5625e9267c44b0225bfc71ce99891c833461bc7e549480a4dda96f51fa6db38af8acf2a0d816da224e2",
          "sha256": "2bfd6491ee0f01061fb7a485dd07daeddde0011bd5bb5523e07b6497cebca70e",
          "sha1": "d98975ec89c93fda95ed3ddcb3484d3c7274daad",
          "md5": "d2165072a7c57dd18054827859360cfb"
        }
      ]
    }
  ]
}
