{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.mailcomposer",
    "version": "14.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.mailcomposer-14.1.4.aar",
          "url": "expo.modules.mailcomposer-14.1.4.aar",
          "size": 26692,
          "sha512": "1148771e76f1a131fbfc06de4fd0a8ac6a22618dbb2e58dbf50c482733a81386201ce22e2c9c577855443e4a25b189390e90a13736c0cf32ee0993d241a7ff43",
          "sha256": "6cd7cb878f734e597e9e243e78d11032d5a37c48ed598cb6e2000b8ce2df4487",
          "sha1": "fc197b67eda6952b76619cf00259b6a686b46d6e",
          "md5": "94551e9f0a412ed9243fe73800b4a77d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.mailcomposer-14.1.4.aar",
          "url": "expo.modules.mailcomposer-14.1.4.aar",
          "size": 26692,
          "sha512": "1148771e76f1a131fbfc06de4fd0a8ac6a22618dbb2e58dbf50c482733a81386201ce22e2c9c577855443e4a25b189390e90a13736c0cf32ee0993d241a7ff43",
          "sha256": "6cd7cb878f734e597e9e243e78d11032d5a37c48ed598cb6e2000b8ce2df4487",
          "sha1": "fc197b67eda6952b76619cf00259b6a686b46d6e",
          "md5": "94551e9f0a412ed9243fe73800b4a77d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.mailcomposer-14.1.4-sources.jar",
          "url": "expo.modules.mailcomposer-14.1.4-sources.jar",
          "size": 4350,
          "sha512": "8c6cbf4b2d33757d2be99732f64b193f7b231e2a95cd03796199509b29a5a3895acbab427ef9ab2deecf84f8036e3254acf20a06bed09d914adbe08b4c4b64e4",
          "sha256": "570ff537446a59f0a42236b18e1c527cff1b05b22d870381c9c01cd18c3c2368",
          "sha1": "1644105ca961d167d94a051b3fa441e842f2f3e0",
          "md5": "8085dadd363bb2630f2181a13e8324b6"
        }
      ]
    }
  ]
}
