{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.calendar",
    "version": "14.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo.modules.calendar-14.1.4.aar",
          "url": "expo.modules.calendar-14.1.4.aar",
          "size": 130425,
          "sha512": "05c3821e5964e04e76e4f644845afd609a286bb7929ab6e958e23497efb79aad22353e6b97f3d3b3af400b89f938762f0f8e11afeda3fe89794a145f0522faf2",
          "sha256": "e60b1e57d6fe17d30ade25e3ea986a533094f0ac34e83536883651cf22fbc546",
          "sha1": "be16e3021c680b615f326f1c3b837840e317d9fc",
          "md5": "38c8bfe3d4cd2bb2b26d1db7c0d3325b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.calendar-14.1.4.aar",
          "url": "expo.modules.calendar-14.1.4.aar",
          "size": 130425,
          "sha512": "05c3821e5964e04e76e4f644845afd609a286bb7929ab6e958e23497efb79aad22353e6b97f3d3b3af400b89f938762f0f8e11afeda3fe89794a145f0522faf2",
          "sha256": "e60b1e57d6fe17d30ade25e3ea986a533094f0ac34e83536883651cf22fbc546",
          "sha1": "be16e3021c680b615f326f1c3b837840e317d9fc",
          "md5": "38c8bfe3d4cd2bb2b26d1db7c0d3325b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.calendar-14.1.4-sources.jar",
          "url": "expo.modules.calendar-14.1.4-sources.jar",
          "size": 16371,
          "sha512": "0ff4fce19c7db4450767904ae325f6ad95d15e8b6555c0a96ae4b03cea8960e2af9c069477a3dc57a70b574605e5e01689c771c855f60078499eaa59a1af3bd8",
          "sha256": "7400019eebf1b8e38a89c0a7d92e5671aa120f738766386f1321cbcc8f49928b",
          "sha1": "38e42a176c9b0192f13e7bb31c14e90e2843ca5d",
          "md5": "977b2aa6eea6164f6ac88d976d4bc1a4"
        }
      ]
    }
  ]
}
